# 복습

## 주피터 노트북 사용법

cell : 코드 실행하는 하나의 작은 상자

단축키
- [shift] + [enter] : 셀 실행
- [alt] + [enter] : 하단에 셀 추가하며 셀 실행
- [esc] + [m] : 마크다운
- [esc] + [y] : 코드모드
- [ctrl] + [/] : 주석모드

## 파이썬 기초 문법
- 변수 : 데이터 담는 상자

## 자료구조
- 리스트 : []
- 튜플 : ()
- 세트 : {}
- 딕셔너리 : {키 : 벨류, 키2 : 벨류2, ...}

In [24]:
dict1 = {'이름':'홍길동','나이':25}
dict1

{'이름': '홍길동', '나이': 25}

In [3]:
dict1['이름']

'홍길동'

In [4]:
input1 = input()
input1

 45


'45'

In [5]:
type(input1) #기본적으로 스트링 형태로 받는다

str

In [6]:
input2 = int(input('숫자를 입력하시오'))
type(input2)

숫자를 입력하시오 34


int

## 조건문
- if / else/ elif
- in / not in
- pass

In [7]:
data1 = int(input())
if data1 > 20:
    print('30보다 큽니다')
else:
    print('30보다 작습니다')

 50


30보다 큽니다


In [9]:
data1 = 0
while data1 < 10:
    data1 = data1 + 1
    print(data1)

1
2
3
4
5
6
7
8
9
10


In [10]:
for i in ['a','b','c']:
    print(i)

a
b
c


In [11]:
# 리스트 컴프리헨션
[x for x in range(6)]

[0, 1, 2, 3, 4, 5]

In [13]:
# 똑같은 코드
for i in range(6):
    print(i,end=' ')

0 1 2 3 4 5 

## 함수
- def
- return

In [14]:
def func1(x):
    return x+200
func1(2)

202

In [15]:
def func2(x1,x2,cond1=True):
    if cond1 == True:
        return x1+x2
    else:
        return x1-x2

In [17]:
func2(100,200,-1)

-100

## 예외처리
- try : 시도 코드
- except : 에러난 경우 실행
- finally : 에러 상관 없이 최종 실행

In [23]:
try:
    data1 = []
    for i in range(1,6):
        data1.remove(1)
        data1.append(i)
    print('no error')
except Exception as e:
    print('error : ', e)
finally:
    print(data1)
    print('done')

error :  list.remove(x): x not in list
[]
done


# 미션풀이

## 1. for 반복문으로 특정 리스트 내의 모든 숫자 합을 계산하는 함수를 구성하시오

- 숙련자 : input 함수를 이용하고, 함수로 구성

In [27]:
lst = [x for x in range(101)]
sum = 0

for i in lst:
    sum += i
print(sum)

5050


In [36]:
input_number = input()
input_lst = input_number.split()
input_lst

 1 2 3 4 5


['1', '2', '3', '4', '5']

In [37]:
lst2 =[int(x) for x in input_lst]

In [38]:
def sum_lst(lst):
    sum = 0
    for i in range(len(lst)):
        sum += lst[i]
    return sum

In [39]:
sum_lst(lst2)

15

## 2. for 반복문으로 특정 리스트 안에 있는 모든 숫자의 평균을 계산하는 함수를 구성하시오
- 숙련자 : input 함수를 이용하고 함수로 구성

In [46]:
lst = [x for x in range(101)]
sum_lst(lst)/len(lst)

50.0

In [48]:
input_number = input()
lst1 = input_number.split()
lst2 = [int(x) for x in lst1]

print(sum_lst(lst2) / len(lst2))

 1 2 3


2.0


## 3. 성적처리 함수를 만들고자 한다.
- 학생이 입력한 값의 평균을 계산해서 90점 이상이면 A / 80점 이상이면 B / 70점 이상이면 C / 나머지는 D 를 출력하는 함수를 구성
    - 입력값 (input) / 5개의 숫자 값을 입력 / 띄어쓰기로 구분하여 입력
    - 입력값에 학생이름도 포함
        - ex) 홍길동 100 90 54 90 34
    - 출력 : 홍길동 학생의 평균은 00 입니다. 학점은 00입니다.

In [52]:
input_data = input('이름과 성적 5개를 입력하시오 : ')
input_lst = input_data.split()

name = input_lst[0]
scores = input_lst[1:] 

scores = [int(x) for x in scores]

avg = sum_lst(scores) / len(scores)

if avg>=90:
    score = "A"
elif avg>=80:
    score = "B"
elif avg>=70:
    score = "C"
else:
    score = "D"

print(f"{name}학생의 평균은 {avg} 입니다. 학점은 {score}입니다.")

이름과 성적 5개를 입력하시오 :  김지수 40 50 80 90 100


김지수학생의 평균은 72.0 입니다. 학점은 C입니다.


## 2. for 반복문으로 특정 리스트 안에 있는 모든 숫자의 평균을 계산하는 함수를 구성하시오
- 숙련자 : input 함수를 이용하고 함수로 구성

In [54]:
input_year = int(input('년도를 입력하시오 '))
if ((input_year%4==0)&(input_year%100!=0)) | (input_year%400==0):
    info = '윤년'
else:
    info = '평년'
print(f"{input_year}은 {info}입니다")

년도를 입력하시오  2020


2020은 윤년입니다


In [56]:
input_year = int(input("연도를 입력하시오"))
dict1 = {True:'윤년',False :'평년'}
bool1 = (input_year%4==0 and input_year%100!=0) or input_year%400==0 # bool
info = dict1[bool1]

print(f"{input_year}은 {info}입니다")

연도를 입력하시오 2030


2030은 평년입니다


## numpy
- 정형데이터의 기본이 되는 형태
- 초기 데이터 분석에 많이 쓰였지만, 지금은 비정형 데이터에 주로 쓰인다.

# 데이터 분석 라이브러리
- numpy(numeric + python) : 연속형, 수치형 자료의 과학/통계/수학 연산을 수행하는 라이브러리, 고차원 배열 다룰 수 있음.
  딥러닝, 비정형 데이터를 다루는데 많이 쓰임

- pandas(panel + dataset) : 정형데이터 (exel, csv, rdb, sql, .... )를 다루는 라이브러리

- matplot(matlab + plot) : 요즘은 많이 안 씀, 연속형 데이터 그래프 시각화 라이브러리

#### 요즘 많이 쓰는 시각화 라이브러리
- seaborn : 정형데이터 통계분석 시각화 라이브러리
- plotly : 정형데이터 동적 시각화 라이브러리
- missingno : 결측치 패턴, 수 시각화 라이브러리
- scipy(science + python) : 응용통계(가설검정/회귀분석/시계열/...) 라이브러리

- scikit-learn(science + python + toolkit + learning) : 정형 데이터를 이용한 데이터 마이닝, 머신러닝 라이블러리

#### 딥러닝 라이브러리
- tensorflow : 비정형 데이터 라이브러리
- keras : tensorflow 기반 딥러닝 학습 라이브러리
- pytorch : 비정형 데이터 관련 라이브러리
- konlpy(korean natural language processiong pyhton) : 한국어 자연어 처리 라이브러리

In [60]:
import numpy as np

lst1 = [1,3,5]
# list1.mean() # 오류 : 리스트의 계산은 할 수 없음

In [61]:
data1 = np.array([1,2,3]) # 넘파이 형태로 지정하면 계산 쉽게 할 수 있다.
type(data1)

numpy.ndarray

In [63]:
data1.mean() # 넘파이는 수치 연산 바로 된다 

2.0

In [64]:
data1.max()

3

In [65]:
[x for x in range(0,10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [66]:
np.arange(10) # range랑 비슷함

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
np.arange(1,20,3) 

array([ 1,  4,  7, 10, 13, 16, 19])

In [69]:
np.linspace(1,10,7) # 1 - 10까지 7로 쪼개서 냄

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [70]:
data1.ndim # 배열의 차원 수

1

In [1]:
# 0 : scalar
# 1 : vector
# 2 : matrix
# 3: tensor

In [2]:
# 행렬 
# 행 : 행거 - 가로
# 열 : 열쇠 - 세로

In [3]:
m1 = [ [0,0,1], [0,1,0], [1,0,0] ]
m1

[[0, 0, 1], [0, 1, 0], [1, 0, 0]]

In [5]:
import numpy as np 

data1 = np.array(m1)
data1

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

In [6]:
type(data1)

numpy.ndarray

In [7]:
data1.ndim

2

In [9]:
# 행렬 연산
data4 = np.array( [[1,2],[3,4],[5,6]] ) # 3*2
data5 = np.array( [[1,2],[3,4],[5,6]] ) # 3*2
data4 + data5

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [11]:
# 행렬 곱 : 앞의 행, 뒤의 열 같아야 곱해진다

data6 = np.array([[1,2],[3,4],[5,6]])
data7 = np.array([[1,2,3],[4,5,6]])

In [14]:
data6@data7 # 곱연산 @

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [15]:
# 매트릭스 인덱싱
data5 = np.array([['a','b','c'],['d','e','f'],['g','h','i']])
data5

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i']], dtype='<U1')

In [16]:
data5[0]

array(['a', 'b', 'c'], dtype='<U1')

In [19]:
data5[:,0] # : 모든행, 0 : 첫번째 열

array(['a', 'd', 'g'], dtype='<U1')

In [20]:
data5[0,0]='z'
data5

array([['z', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i']], dtype='<U1')

In [21]:
data5[1]=['x','y','z']
data5

array([['z', 'b', 'c'],
       ['x', 'y', 'z'],
       ['g', 'h', 'i']], dtype='<U1')

In [24]:
# 두 글자 넣어놔도 한글자밖에 출력을 못한다
data5[0,0] = 'a1'
data5

array([['a', 'b', 'c'],
       ['x', 'y', 'z'],
       ['g', 'h', 'i']], dtype='<U1')

In [28]:
data6 = np.array(data5,dtype='<U2')
data6[0,0] = 'a1'
data6

array([['a1', 'b', 'c'],
       ['x', 'y', 'z'],
       ['g', 'h', 'i']], dtype='<U2')

In [29]:
data7

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
np.vstack( [data7,[1,2,3]] ) # 열에 추가됨

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [35]:
np.hstack([data7,[[1],[2]]]) # 행에 추가됨

array([[1, 2, 3, 1],
       [4, 5, 6, 2]])

In [36]:
# 재구조화
data8 = np.array([1,25,25,1])
data8

array([ 1, 25, 25,  1])

In [38]:
data8.reshape(2,2) # 벡터 형태가 행렬형태가 됬음

array([[ 1, 25],
       [25,  1]])

In [39]:
data9 = np.linspace(1,25,9) # 1-25 9개
data9

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25.])

In [40]:
data9.reshape(3,3)

array([[ 1.,  4.,  7.],
       [10., 13., 16.],
       [19., 22., 25.]])

In [44]:
data11 = np.random.rand(2,3) # 랜덤으로도 매트릭스 생성가능
data11

array([[0.67369994, 0.64699309, 0.72384574],
       [0.88611801, 0.53031141, 0.67463873]])

In [45]:
data11.sum()

4.135606914401948

In [46]:
data11.mean()

0.6892678190669913

In [47]:
# 열, 행 별로의 연산
data11.sum(axis = 0) # 열단위로 합

array([1.55981795, 1.1773045 , 1.39848447])

In [48]:
data11.sum(axis = 1) # 행단위로 합

array([2.04453877, 2.09106814])

In [49]:
data11.mean(axis = 0) # 열단위로 합

array([0.77990897, 0.58865225, 0.69924223])

In [50]:
data11.max()

0.8861180093169545

In [51]:
data11.max(axis=0)

array([0.88611801, 0.64699309, 0.72384574])

In [52]:
data11.min()

0.5303114054231919

## pandas
- series : 데이터 타입, numpy의 array기반으로 만들어진 정형데이터분석을 위해 구성된 index-value형식의 자료구조
- dataframe : 이차원 자료구조를 위한 자료구조

In [85]:
import pandas as pd

s1 = pd.Series([1,2,3]) # 0,1,2에 대응하는 값
s1

0    1
1    2
2    3
dtype: int64

In [60]:
s2 = pd.Series(['a','b','c',4])
s2
# 숫자형 : int,float
# 문자형 : object, str
# object : 집단이 문자열이다, 4 또한 문자열로 인식하고 있다

# 시리즈는 하나의 데이터 타입만 올 수 있다

0    a
1    b
2    c
3    4
dtype: object

In [62]:
s2.index # 0부터 4까지 상승하고 있습니다.

RangeIndex(start=0, stop=4, step=1)

In [63]:
s2.values

array(['a', 'b', 'c', 4], dtype=object)

In [65]:
type(s2) # 데이터 타입을 자주 확인하는 것이 좋다

pandas.core.series.Series

In [67]:
type(s1.values) # 시리즈 데이터는 넘파이 어레이 기반으로 되어 있구나!

numpy.ndarray

In [68]:
# 시리즈의 인덱싱과 슬라이스
s2


0    a
1    b
2    c
3    4
dtype: object

In [69]:
s2[0]

'a'

In [71]:
s2[0:2] # [n:m] : n부터 m-1까지만 호출된다

0    a
1    b
dtype: object

In [75]:
s1[0] = 99
s1

0    99
1     2
2     3
dtype: int64

In [78]:
s1.drop(0) # 삭제 - but 원본을 삭제해주는게 아니라 카피본의 첫번째 삭제해줌

1    2
2    3
dtype: int64

In [86]:
s3 = s1.drop(0,inplace=True) # 인플레이스 옵션 사용시, 원본 변수에 수정을 함

In [88]:
s1

1    2
2    3
dtype: int64

In [90]:
# 인덱스 지정
s4 = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])

In [91]:
s4

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [94]:
#인덱싱
s4['a'] # 인덱스의 이름으로 값 보기

1

In [95]:
# 딕셔너리로 시리즈 구성
s5 = pd.Series({'name':'둘리','age':5,'area':'서울'})
s5

name    둘리
age      5
area    서울
dtype: object

In [96]:
# 인덱스 이름 변경
s6 = s5.rename(index = {'name':'이름'})
s6 

이름      둘리
age      5
area    서울
dtype: object

In [97]:
s5.rename(index = {'name':'이름'}, inplace=True)

In [98]:
s5

이름      둘리
age      5
area    서울
dtype: object

In [99]:
# 새로운 값 추가
s5['친구'] = '희동이'
s5

이름       둘리
age       5
area     서울
친구      희동이
dtype: object

In [103]:
df = pd.DataFrame([100,200,300,400])
df

0
0  100
1  200
2  300
3  400

In [101]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [105]:
# 컬럼이라는 개념이 있음 시리즈 여러개 -> 컬럼
df.columns

RangeIndex(start=0, stop=1, step=1)

In [106]:
df.values

array([[100],
       [200],
       [300],
       [400]], dtype=int64)

In [108]:
# column을 지정하여 데이터 프레임을 구성
df1 = pd.DataFrame(data=[[100,200,300,400,500], # 이중 리스트로 받으면 누워서 받게 됨
                         [40,200,22,22,23]],
                   columns=['A','B','C','D','E'])
df1         

A    B    C    D    E
0  100  200  300  400  500
1   40  200   22   22   23

In [109]:
df1.index

RangeIndex(start=0, stop=2, step=1)

In [110]:
df1.columns

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [111]:
df1['A']

0    100
1     40
Name: A, dtype: int64

In [112]:
type(df1['A'])

pandas.core.series.Series

In [113]:
df1['A'].index

RangeIndex(start=0, stop=2, step=1)

In [114]:
df1['A'].values

array([100,  40], dtype=int64)

In [115]:
df1[['A','B']]

A    B
0  100  200
1   40  200

In [117]:
df1[['A']] 
# 이중리스트로 하나의 컬럼을 호출하는 경우
# 데이터 프레임 형태로 호출해준다

A
0  100
1   40

In [121]:
# column을 지정하여 데이터 프레임을 구성
df2 = pd.DataFrame(data=[['오덕이',100,80,70], # 이중 리스트로 받으면 누워서 받게 됨
                         ['이기영',70,60,70],
                        ['이기철',60,70,80]],
                   columns=['이름','국어','수학','체육'])
df2         

이름   국어  수학  체육
0  오덕이  100  80  70
1  이기영   70  60  70
2  이기철   60  70  80

In [122]:
df1.index

RangeIndex(start=0, stop=2, step=1)

In [124]:
df2.values # 각각의 시리즈 출력

array([['오덕이', 100, 80, 70],
       ['이기영', 70, 60, 70],
       ['이기철', 60, 70, 80]], dtype=object)

In [125]:
df2.columns

Index(['이름', '국어', '수학', '체육'], dtype='object')

In [126]:
df2['이름']

0    오덕이
1    이기영
2    이기철
Name: 이름, dtype: object

In [127]:
df2.iloc[0] # index location

이름    오덕이
국어    100
수학     80
체육     70
Name: 0, dtype: object

In [131]:
df2.iloc[2].values

array(['이기철', 60, 70, 80], dtype=object)

In [133]:
df2.set_index('이름',inplace=True)

In [137]:
df2.iloc[0] # 숫자만 입력 가능 , iloc : 행 빼주는거

국어    100
수학     80
체육     70
Name: 오덕이, dtype: int64

In [136]:
df2.loc['오덕이'] # loc: 문자도 입력 가능함, 행 추출

국어    100
수학     80
체육     70
Name: 오덕이, dtype: int64

In [138]:
# 딕셔너리로 데이터 프레임 생성
# 키값이 컬럼명으로 들어가고
# 벨류값은 컬럼의 값들로 채워진다

df3 = pd.DataFrame(data = {'장르':['팝','록'],
                          '아티스트':['마잭','비틀즈'],
                          '곡':['rock with you','julia']})
df3

장르 아티스트              곡
0  팝   마잭  rock with you
1  록  비틀즈          julia

# DDA
- 기술적 데이터 분석 (descriptive data analysis)
- 비즈니스 목표에 부합하는 변수 확인
- 목표변수 Y (target, label, output, ....)
- 설명변수 X (feature, input, ....)
- 기술통계량 확인 (평균 / 중위수 / 분산 / ..)

## 01_Data.csv
- 사무용품을 렌탈해주는 업체의 고객 데이터

In [141]:
df1 = pd.read_csv('01_Data.csv')

# 데이터의 구조와 타입을 확인 
- index - column - value를 확인
- index : 데이터의 개수를 확인 
    - 데이터의 개수에 따라 분석 방법이 달라짐
- column : 데이터의 열 / 데이터의 항목
    - 각 항목별(열) 데이터 타입을 확인
        - 연속형 : int/float
        - 범주형 : object
        - 순서형 : 날짜 / 시간 데이터 (datetime)
- value : 값 
    - 데이터의 형식 (format) 확인
    - 원시자료설명서 / DB설계서 / 변수정의서 확인 (데이터가 의미하는 바 알 수 O)
    - 결측값(missing value) : 데이터 수집 중 오류나 누락으로 인해 비어있는 값 
                              ex) None/NaN(not a number)/Na(not available)/null/inf ...

In [143]:
df1.index

RangeIndex(start=0, stop=51301, step=1)

In [145]:
df1.shape # 행렬확인

(51301, 20)

In [146]:
df1.columns # 항목확인

Index(['Index', 'Member_ID', 'Sales_Type', 'Contract_Type', 'Channel',
       'Datetime', 'Term', 'Payment_Type', 'Product_Type', 'Amount_Month',
       'Customer_Type', 'Age', 'Address1', 'Address2', 'State',
       'Overdue_count', 'Overdue_Type', 'Gender', 'Credit_Rank', 'Bank'],
      dtype='object')

In [147]:
len(df1) # index 확인 가능

51301

In [151]:
df1.info() # 결측치, 데이터 항목, 데이터 자료형 확인 가능

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51301 entries, 0 to 51300
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Index          51301 non-null  int64  
 1   Member_ID      51301 non-null  int64  
 2   Sales_Type     51301 non-null  object 
 3   Contract_Type  51301 non-null  object 
 4   Channel        51301 non-null  object 
 5   Datetime       51301 non-null  object 
 6   Term           51301 non-null  int64  
 7   Payment_Type   51301 non-null  object 
 8   Product_Type   51301 non-null  object 
 9   Amount_Month   51301 non-null  int64  
 10  Customer_Type  51299 non-null  object 
 11  Age            44329 non-null  float64
 12  Address1       51299 non-null  object 
 13  Address2       51299 non-null  object 
 14  State          51301 non-null  object 
 15  Overdue_count  51301 non-null  int64  
 16  Overdue_Type   51301 non-null  object 
 17  Gender         51301 non-null  object 
 18  Credit

In [155]:
# 결측치 확인
df1.isnull().sum() # isnull : 참 거짓으로 나옴, sum() : null값 개수 확인

Index               0
Member_ID           0
Sales_Type          0
Contract_Type       0
Channel             0
Datetime            0
Term                0
Payment_Type        0
Product_Type        0
Amount_Month        0
Customer_Type       2
Age              6972
Address1            2
Address2            2
State               0
Overdue_count       0
Overdue_Type        0
Gender              0
Credit_Rank      8781
Bank             2759
dtype: int64

In [156]:
# 데이터 추출
df1.head()
#head : 대표로 앞에서 5줄만 보여준다 기본값이 5 


Index  Member_ID Sales_Type Contract_Type Channel    Datetime  Term  \
0      1   66758234         렌탈          일반계약    영업방판  2022-05-05    60   
1      2   66755948         렌탈          교체계약    영업방판  2023-02-19    60   
2      3   66756657         렌탈          일반계약  홈쇼핑/방송  2022-02-27    60   
3      4   66423450        멤버십        멤버십3유형     재계약  2022-05-12    12   
4      5   66423204        멤버십        멤버십3유형     재계약  2022-05-09    12   

  Payment_Type Product_Type  Amount_Month Customer_Type   Age Address1  \
0          CMS        DES-1         96900            개인  42.0      경기도   
1         카드이체        DES-1        102900            개인  39.0      경기도   
2          CMS        DES-1         96900            개인  48.0      경기도   
3          CMS        DES-1         66900            개인  39.0      경기도   
4          CMS        DES-1         66900            개인  60.0      경기도   

  Address2 State  Overdue_count Overdue_Type Gender  Credit_Rank    Bank  
0      경기도  계약확정              0           없음     여자          9.0   새마을금고  
1      경기도  계약확정              0           없음     남자          2.0    현대카드  
2      경기도  계약확정              0           없음     여자          8.0    우리은행  
3      경기도  계약확정              0           없음     남자          5.0  농협회원조합  
4      경기도  기간만료             12           있음     남자          8.0  농협회원조합

In [157]:
df1.head(10)

Index  Member_ID Sales_Type Contract_Type Channel    Datetime  Term  \
0      1   66758234         렌탈          일반계약    영업방판  2022-05-05    60   
1      2   66755948         렌탈          교체계약    영업방판  2023-02-19    60   
2      3   66756657         렌탈          일반계약  홈쇼핑/방송  2022-02-27    60   
3      4   66423450        멤버십        멤버십3유형     재계약  2022-05-12    12   
4      5   66423204        멤버십        멤버십3유형     재계약  2022-05-09    12   
5      6   66165241         렌탈        프로모션계약    영업방판  2022-07-28    60   
6      7   66751017         렌탈         패키지계약  홈쇼핑/방송  2022-01-29    60   
7      8   66751017         렌탈         패키지계약  홈쇼핑/방송  2022-01-16    60   
8      9   66758007         렌탈          일반계약    영업방판  2022-06-29    60   
9     10   66756702         렌탈        프로모션계약    영업방판  2022-06-29    60   

  Payment_Type Product_Type  Amount_Month Customer_Type   Age Address1  \
0          CMS        DES-1         96900            개인  42.0      경기도   
1         카드이체        DES-1        102900            개인  39.0      경기도   
2          CMS        DES-1         96900            개인  48.0      경기도   
3          CMS        DES-1         66900            개인  39.0      경기도   
4          CMS        DES-1         66900            개인  60.0      경기도   
5          CMS       DES-3A         90900            개인  53.0      경상도   
6         카드이체        DES-1         98400            개인  66.0      경상도   
7         카드이체        DES-2         80400            개인  66.0      경상도   
8         카드이체       DES-3A        102900            개인  62.0      경상도   
9          CMS        DES-1        105900            개인  51.0      경상도   

  Address2 State  Overdue_count Overdue_Type Gender  Credit_Rank    Bank  
0      경기도  계약확정              0           없음     여자          9.0   새마을금고  
1      경기도  계약확정              0           없음     남자          2.0    현대카드  
2      경기도  계약확정              0           없음     여자          8.0    우리은행  
3      경기도  계약확정              0           없음     남자          5.0  농협회원조합  
4      경기도  기간만료             12           있음     남자          8.0  농협회원조합  
5      경상도  계약확정              0           없음     여자          5.0   농협중앙회  
6      경상도  계약확정              0           없음     남자          1.0    롯데카드  
7      경상도  계약확정              0           없음     남자          1.0    롯데카드  
8      경상도  계약확정              0           없음     여자          2.0    롯데카드  
9      경상도  계약확정              0           없음     여자          1.0    신한은행

In [158]:
# 뒤에서 부터 확인
df1.tail()

Index  Member_ID Sales_Type Contract_Type Channel    Datetime  Term  \
51296  51298   66579515         렌탈        프로모션계약   대형마트A  2022-02-28    60   
51297  51299   66799558         렌탈          일반계약   대형마트A  2022-03-31    60   
51298  51300   66799197         렌탈        프로모션계약    영업방판  2022-03-31    39   
51299  51301   66792778         렌탈          일반계약  홈쇼핑/방송  2023-02-05    60   
51300  51302   66799607         렌탈          일반계약  홈쇼핑/방송  2022-04-23    60   

      Payment_Type Product_Type  Amount_Month Customer_Type   Age Address1  \
51296          CMS       DES-3A         96900            개인  47.0      경기도   
51297          CMS        DES-1         96900            개인  42.0      경기도   
51298         카드이체          ERA        120900            개인  65.0    서울특별시   
51299         카드이체        DES-1         96900            개인  54.0    서울특별시   
51300          CMS        DES-1         96900            개인  53.0    서울특별시   

      Address2 State  Overdue_count Overdue_Type Gender  Credit_Rank   Bank  
51296      경기도  계약확정              0           없음     남자          NaN   기업은행  
51297      경기도  계약확정              0           없음     여자          8.0  새마을금고  
51298    서울특별시  계약확정              0           없음     여자          1.0   롯데카드  
51299    서울특별시  계약확정              0           없음     여자          2.0   롯데카드  
51300    서울특별시  계약확정              0           없음     여자          8.0   신한은행

In [164]:
df1.iloc[50:61]

Index  Member_ID Sales_Type Contract_Type Channel    Datetime  Term  \
50     51   66758548         렌탈          일반계약    영업방판  2022-03-30    60   
51     52   66758162         렌탈         패키지계약  홈쇼핑/방송  2022-10-02    60   
52     53   66758162         렌탈         패키지계약  홈쇼핑/방송  2022-05-03    60   
53     54   66590304         렌탈        프로모션계약    영업방판  2021-12-31    60   
54     55   66670488         렌탈        프로모션계약    영업방판  2022-04-02    60   
55     56   25856039         렌탈          교체계약    영업방판  2022-04-30    60   
56     57   25869517         렌탈        프로모션계약    영업방판  2022-07-21    60   
57     58   66757967         렌탈        프로모션계약    영업방판  2022-08-20    60   
58     59   66260467         렌탈          교체계약    영업방판  2022-02-15    60   
59     60   66758899         렌탈         패키지계약   전문매장H  2022-07-29    60   
60     61   66758899         렌탈         패키지계약   전문매장H  2023-01-21    60   

   Payment_Type Product_Type  Amount_Month Customer_Type   Age Address1  \
50          CMS        DES-1         96900            개인  57.0    서울특별시   
51         카드이체        DES-1         98400            개인  50.0    서울특별시   
52         카드이체        DES-2         80400            개인  50.0    서울특별시   
53          CMS        DES-2         90900            개인  43.0    서울특별시   
54          CMS        DES-1         96900            개인  34.0    서울특별시   
55          CMS        DES-1         96900           사업자   NaN      경상도   
56         가상계좌        DES-1         96900           사업자   NaN      경상도   
57         카드이체        DES-1        105900            개인  37.0      경상도   
58          CMS        DES-1         96900            개인  42.0      경상도   
59          CMS        DES-1         81900            개인  67.0      경상도   
60          CMS        DES-2         81900            개인  67.0      경상도   

   Address2 State  Overdue_count Overdue_Type Gender  Credit_Rank   Bank  
50    서울특별시  계약확정              0           없음     남자          4.0   국민은행  
51    서울특별시  계약확정              0           없음     남자          5.0   국민카드  
52    서울특별시  계약확정              0           없음     남자          5.0   국민카드  
53    서울특별시  계약확정              0           없음     남자          4.0   신한은행  
54    서울특별시  계약확정              0           없음     여자          4.0   우리은행  
55    부산광역시  계약확정              0           없음     여자          NaN  농협중앙회  
56    부산광역시  계약확정              0           없음     여자          NaN    NaN  
57      경상도  계약확정              0           없음     여자          5.0   롯데카드  
58      경상도  계약확정              0           없음     여자          1.0   우리은행  
59      경상도  계약확정              0           없음     남자          2.0   대구은행  
60      경상도  계약확정              0           없음     남자          2.0   대구은행

In [161]:
# 엑셀로 저장
df1.iloc[50:61].to_excel('result.xlsx')

In [162]:
df1.iloc[50:61].to_csv('result_1.xlsx')

In [165]:
# 열 단위 추출
df1['Amount_Month']

0         96900
1        102900
2         96900
3         66900
4         66900
          ...  
51296     96900
51297     96900
51298    120900
51299     96900
51300     96900
Name: Amount_Month, Length: 51301, dtype: int64

In [166]:
# 이중리스트 사용 시 데이터 프레임 형태로 출력
# 여러 컬럼을 출력하는 경우에도 이중 리스트 사용
df1[['Amount_Month']]

Amount_Month
0             96900
1            102900
2             96900
3             66900
4             66900
...             ...
51296         96900
51297         96900
51298        120900
51299         96900
51300         96900

[51301 rows x 1 columns]

In [167]:
df1[['Age','Amount_Month']]

Age  Amount_Month
0      42.0         96900
1      39.0        102900
2      48.0         96900
3      39.0         66900
4      60.0         66900
...     ...           ...
51296  47.0         96900
51297  42.0         96900
51298  65.0        120900
51299  54.0         96900
51300  53.0         96900

[51301 rows x 2 columns]

In [169]:
# 열단위 추출 후 csv파일로 저장
df1[['Age','Amount_Month']].head(100).to_csv('age_100.csv')

## 데이터 정렬
- .sort_values(옵션 by=,ascending = False)

In [170]:
df1.sort_values(by='Amount_Month') # 디폴트 오름차순

Index  Member_ID Sales_Type Contract_Type Channel    Datetime  Term  \
35768  35770   66784964        멤버십        멤버십2유형   전문매장H  2022-02-06    36   
43022  43024   66792946        멤버십        멤버십2유형   전문매장H  2023-06-30    36   
49993  49995   66796388        멤버십        멤버십2유형   전문매장H  2023-03-25    36   
33803  33805   66783630        멤버십        멤버십2유형   전문매장H  2023-07-28    36   
45246  45248   66793779        멤버십        멤버십2유형   전문매장H  2022-07-15    36   
...      ...        ...        ...           ...     ...         ...   ...   
5399    5400   25742182         렌탈        프로모션계약    영업방판  2022-05-17    39   
49896  49898   25731710         렌탈        프로모션계약    영업방판  2022-09-29    39   
49897  49899   25731710         렌탈        프로모션계약    영업방판  2022-12-05    39   
28147  28149   25704137         렌탈        프로모션계약    전단홍보  2022-07-24    39   
38497  38499   25734005         렌탈        프로모션계약    영업방판  2022-06-04    39   

      Payment_Type Product_Type  Amount_Month Customer_Type   Age Address1  \
35768          무통장        DES-1         54603            개인   NaN      경기도   
43022          무통장        DES-1         54603            개인   NaN      전라도   
49993          무통장        DES-1         54603            개인   NaN    서울특별시   
33803          무통장        DES-1         54603            개인   NaN      경기도   
45246          무통장        DES-1         54603            개인   NaN    서울특별시   
...            ...          ...           ...           ...   ...      ...   
5399           CMS          MMC        215700           사업자   NaN      경기도   
49896         가상계좌          MMC        215700           사업자   NaN      경기도   
49897         가상계좌          MMC        215700           사업자   NaN      경기도   
28147          CMS          MMC        215700           사업자   NaN      경상도   
38497          CMS          MMC        215700           사업자  58.0      전라도   

      Address2 State  Overdue_count Overdue_Type Gender  Credit_Rank   Bank  
35768      경기도  계약확정              0           없음     여자          NaN    NaN  
43022    광주광역시  계약확정              0           없음     여자          NaN    NaN  
49993    서울특별시  계약확정              0           없음     여자          NaN    NaN  
33803    인천광역시  계약확정              0           없음     여자          NaN    NaN  
45246    서울특별시  계약확정              0           없음     여자          NaN    NaN  
...        ...   ...            ...          ...    ...          ...    ...  
5399       경기도  계약확정              1           있음     여자          NaN   신한은행  
49896      경기도  계약확정              0           없음     여자          NaN    NaN  
49897      경기도  계약확정              0           없음     여자          NaN    NaN  
28147      경상도  계약확정              0           없음     여자          NaN   국민은행  
38497      전라도  계약확정              0           없음     남자          1.0  농협중앙회  

[51301 rows x 20 columns]

In [171]:
# 내림차순 옵션 ascending = False
df1.sort_values(by = 'Amount_Month',ascending=False)

Index  Member_ID Sales_Type Contract_Type Channel    Datetime  Term  \
19773  19775   25740247         렌탈        프로모션계약    전단홍보  2022-11-13    39   
28147  28149   25704137         렌탈        프로모션계약    전단홍보  2022-07-24    39   
19413  19415   25710320         렌탈        프로모션계약    영업방판  2023-01-28    39   
19412  19414   25710321         렌탈        프로모션계약    영업방판  2022-09-14    39   
37522  37524   25733781         렌탈        프로모션계약    영업방판  2023-07-02    39   
...      ...        ...        ...           ...     ...         ...   ...   
45304  45306   66793756        멤버십        멤버십2유형   전문매장H  2022-10-06    36   
50428  50430   66797402        멤버십        멤버십2유형   전문매장H  2022-12-26    36   
45302  45304   66793342        멤버십        멤버십2유형   전문매장H  2022-04-02    36   
41153  41155   66790864        멤버십        멤버십2유형   전문매장H  2022-02-15    36   
39373  39375   66788207        멤버십        멤버십2유형   전문매장H  2023-05-11    36   

      Payment_Type Product_Type  Amount_Month Customer_Type  Age Address1  \
19773         가상계좌          MMC        215700           사업자  NaN      경상도   
28147          CMS          MMC        215700           사업자  NaN      경상도   
19413          CMS          MMC        215700           사업자  NaN      경기도   
19412          CMS          MMC        215700           사업자  NaN      경기도   
37522          CMS          MMC        215700           사업자  NaN      경기도   
...            ...          ...           ...           ...  ...      ...   
45304          무통장        DES-1         54603            개인  NaN      충청도   
50428          무통장        DES-1         54603            개인  NaN      경기도   
45302          무통장        DES-1         54603            개인  NaN      강원도   
41153          무통장        DES-1         54603            개인  NaN      경기도   
39373          무통장        DES-1         54603            개인  NaN      제주도   

      Address2 State  Overdue_count Overdue_Type Gender  Credit_Rank  Bank  
19773      경상도  계약확정              0           없음     여자          NaN   NaN  
28147      경상도  계약확정              0           없음     여자          NaN  국민은행  
19413      경기도  계약확정              0           없음     여자          NaN  기업은행  
19412      경기도  계약확정              0           없음     여자          NaN  기업은행  
37522      경기도  계약확정              0           없음     여자          NaN  기업은행  
...        ...   ...            ...          ...    ...          ...   ...  
45304      충청도  계약확정              0           없음     여자          NaN   NaN  
50428      경기도  계약확정              0           없음     여자          NaN   NaN  
45302      강원도  계약확정              0           없음     여자          NaN   NaN  
41153      경기도  계약확정              0           없음     여자          NaN   NaN  
39373      제주도  계약확정              0           없음     여자          NaN   NaN  

[51301 rows x 20 columns]

In [173]:
# 여러항목을 기준으로 정렬 
# 월 구매금액 높으면서 연체를 적게 한 사람들 부터 보고자 함
# amount_month, overdue_count 항목 참조
df2 = df1.sort_values(by=['Amount_Month','Overdue_count'],
               ascending=[False,1])

In [174]:
df2[['Amount_Month','Overdue_count']]

Amount_Month  Overdue_count
19412        215700              0
19413        215700              0
19773        215700              0
19774        215700              0
28147        215700              0
...             ...            ...
51277         54603              0
51280         54603              0
51284         54603              0
51290         54603              0
42145         54603              1

[51301 rows x 2 columns]